### PR TITLE
Add Python CI

### PR DESCRIPTION
**Pull request by Swimburger**
Based on the Python API Example docs, install python/anaconda, create/activate environment, and then run linter.

### CODE REVIEW

**Review by trippersham — COMMENTED** [review]
@Swimburger this looks good to me based on the readme! Wondering if we should add pylint for general linting?

My naivete with CI; what happens if mypy or linting fails? How do we configure which kinds of errors we care about?

**Comment by jtuckerk** [comment]
can this be set up to run locally?

In the hf-tech-volunteer repo we used pre-commit to do local linting checking and fixes: https://github.com/HF-RapidResponse/hf-tech-volunteer/blob/master/.pre-commit-config.yaml
I think that was set up before we added the github actions I didnt love having and actions config and a pre-commit config

**Comment by Swimburger** [comment]
That sounds good to me. Do you want to add it to this branch or a separate branch?

**Comment by jtuckerk** [comment]
Let's just leave that for the next PR

**Comment by Swimburger** [comment]
Is this ready to be merged?

**Comment by trippersham** [comment]
Yes!

**Pull request merged**
