### PR TITLE
Replace airtable iframe with role cards

### PR DESCRIPTION
**Pull request by powell759**

### CODE REVIEW

**Comment by powell759** [comment]
Pretty sure the failing check is permissions issue around fetching GCP credentials.

**Comment by ecaoile** [comment]
> 
> 
> Pretty sure the failing check is permissions issue around fetching GCP credentials.

I wonder if this has anything to do with forking it somehow...

**Comment by jtuckerk** [comment]
> > Pretty sure the failing check is permissions issue around fetching GCP credentials.
> 
> I wonder if this has anything to do with forking it somehow...

I think you're probably right, I tried rerunning the checks myself to see if that would do it, but it didnt change it. still got "No credentials provided, skipping authentication" in the Fetch GCP credentials step.

digging in to see what we can do now

**Comment by jtuckerk** [comment]
It looks like they've introduced something that would solve this, but only for private repositories:https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

@powell759 could you add the key [here](https://storage.cloud.google.com/humanity-forward-infra/gcp_credentials.json) to a secret called VOL_PORTAL_GCP_CREDENTIALS in your repo?

**Comment by powell759** [comment]
@jtuckerk I'll add it but if I can get permissions to create branches in the main repo (looks like that's your git flow) - I can just create PRs from there

**Comment by jtuckerk** [comment]
> @jtuckerk I'll add it but if I can get permissions to create branches in the main repo (looks like that's your git flow) - I can just create PRs from there

ah thats definitely easier! Sorry I didnt realize invites expired. I just thought you preferred the Fork flow.
 I just resent the invite.

**Comment by powell759** [comment]
Closing - have access now so opening a pull request from that branch.

**Pull request closed without merging**
