### PR TITLE
Social share image maybe fix

### PR DESCRIPTION
**Pull request by ecaoile**
@trippersham I've changed the content attributes to external URLs. I'm thinking since we're sharing the prod URL, this fix won't really work until we've deployed to prod. Really wish we could test with localhost. The image will still be available in our repo. I've moved it up from being in a pics folder to being directly under the public folder.

### CODE REVIEW

**Comment by jtuckerk** [comment]
Should we make this a hotfix? since I assume we  dont want all of the other dev stuff out in prod yet

**Comment by trippersham** [comment]
Yeah, that makes sense to me

**Comment by ecaoile** [comment]
Uhhh...I forgot how those work. Do we just close this PR then?

**Comment by trippersham** [comment]
We at least need a PR against production, but honestly this is fine to keep open and merge too because we'll need to get it back into develop anyway. @ecaoile could you open one against production as well?

**Comment by trippersham** [comment]
Also @ecaoile are we figuring out the relative paths for static images, or just using the hosted link?

**Comment by ecaoile** [comment]
I changed it to external link just to be safe. Do we run any risk of losing that external host?

**Comment by trippersham** [comment]
Good question. I think safe to assume that's not a risk right now, but we
can check with Caleb for the future.

**Comment by jtuckerk** [comment]
+1, I think the best way is just 2 PRs off this branch.

**Review by jtuckerk — APPROVED** [review]
Looks good to me! I had a few hiccups building it but i think thats cuz docker had taken over the node_modules, but it all seems to be working now.


 social share og images:
image
image

**Review by trippersham — APPROVED** [review]

**Pull request merged**
